#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : apache-flink
Version  : 1.7.2
Release  : 1
URL      : http://github.com/apache/flink/archive/release-1.7.2.tar.gz
Source0  : http://github.com/apache/flink/archive/release-1.7.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CDDL-1.0 CDDL-1.1 MIT MPL-1.1 Python-2.0
Requires: apache-flink-data = %{version}-%{release}
Requires: apache-maven
Requires: cmake
Requires: flink-dep
Requires: openjdk
Requires: openjdk-dev
Requires: openssl-dev
Requires: zlib-dev
BuildRequires : apache-maven
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : flink-dep
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openssl-dev
BuildRequires : zlib-dev
Patch1: 0001-Stateless.patch

%description
# Apache Flink
Apache Flink is an open source stream processing framework with powerful stream- and batch-processing capabilities.

%package data
Summary: data components for the apache-flink package.
Group: Data

%description data
data components for the apache-flink package.


%package doc
Summary: doc components for the apache-flink package.
Group: Documentation

%description doc
doc components for the apache-flink package.


%prep
%setup -q -n flink-release-1.7.2
%patch1 -p1

%build
## build_prepend content
mkdir -p %{buildroot}
cp -r /usr/share/apache-flink/.m2 %{buildroot}/.m2
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559099127
export GCC_IGNORE_WERROR=1
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags} || /usr/bin/mvn package -o -Pnative -Pdist -DskipTests -Dtar -Dmaven.repo.local=%{buildroot}/.m2/repository


%install
export SOURCE_DATE_EPOCH=1559099127
rm -rf %{buildroot}
%make_install ||:
## install_append content
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/flink
cp -r flink-dist/target/flink-*-bin/flink-* %{buildroot}/usr/share/flink
mv %{buildroot}/usr/share/flink/LICENSE %{buildroot}/usr/share/doc/flink/
mv %{buildroot}/usr/share/flink/NOTICE %{buildroot}/usr/share/doc/flink/
mv %{buildroot}/usr/share/flink/README.txt %{buildroot}/usr/share/doc/flink/
mv %{buildroot}/usr/share/flink/licenses %{buildroot}/usr/share/doc/flink/
mkdir -p %{buildroot}/usr/share/defaults/flink
cp  %{buildroot}/usr/share/flink/conf/* %{buildroot}/usr/share/defaults/flink/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/flink/flink-conf.yaml
/usr/share/defaults/flink/log4j-cli.properties
/usr/share/defaults/flink/log4j-console.properties
/usr/share/defaults/flink/log4j-yarn-session.properties
/usr/share/defaults/flink/log4j.properties
/usr/share/defaults/flink/logback-console.xml
/usr/share/defaults/flink/logback-yarn.xml
/usr/share/defaults/flink/logback.xml
/usr/share/defaults/flink/masters
/usr/share/defaults/flink/slaves
/usr/share/defaults/flink/sql-client-defaults.yaml
/usr/share/defaults/flink/zoo.cfg
/usr/share/flink/bin/config.sh
/usr/share/flink/bin/flink
/usr/share/flink/bin/flink-console.sh
/usr/share/flink/bin/flink-daemon.sh
/usr/share/flink/bin/flink.bat
/usr/share/flink/bin/historyserver.sh
/usr/share/flink/bin/jobmanager.sh
/usr/share/flink/bin/mesos-appmaster-job.sh
/usr/share/flink/bin/mesos-appmaster.sh
/usr/share/flink/bin/mesos-taskmanager.sh
/usr/share/flink/bin/pyflink-stream.sh
/usr/share/flink/bin/pyflink.bat
/usr/share/flink/bin/pyflink.sh
/usr/share/flink/bin/sql-client.sh
/usr/share/flink/bin/standalone-job.sh
/usr/share/flink/bin/start-cluster.bat
/usr/share/flink/bin/start-cluster.sh
/usr/share/flink/bin/start-scala-shell.sh
/usr/share/flink/bin/start-zookeeper-quorum.sh
/usr/share/flink/bin/stop-cluster.sh
/usr/share/flink/bin/stop-zookeeper-quorum.sh
/usr/share/flink/bin/taskmanager.sh
/usr/share/flink/bin/yarn-session.sh
/usr/share/flink/bin/zookeeper.sh
/usr/share/flink/conf/flink-conf.yaml
/usr/share/flink/conf/log4j-cli.properties
/usr/share/flink/conf/log4j-console.properties
/usr/share/flink/conf/log4j-yarn-session.properties
/usr/share/flink/conf/log4j.properties
/usr/share/flink/conf/logback-console.xml
/usr/share/flink/conf/logback-yarn.xml
/usr/share/flink/conf/logback.xml
/usr/share/flink/conf/masters
/usr/share/flink/conf/slaves
/usr/share/flink/conf/sql-client-defaults.yaml
/usr/share/flink/conf/zoo.cfg
/usr/share/flink/examples/batch/ConnectedComponents.jar
/usr/share/flink/examples/batch/DistCp.jar
/usr/share/flink/examples/batch/EnumTriangles.jar
/usr/share/flink/examples/batch/KMeans.jar
/usr/share/flink/examples/batch/PageRank.jar
/usr/share/flink/examples/batch/TransitiveClosure.jar
/usr/share/flink/examples/batch/WebLogAnalysis.jar
/usr/share/flink/examples/batch/WordCount.jar
/usr/share/flink/examples/gelly/flink-gelly-examples_2.11-1.7.2.jar
/usr/share/flink/examples/python/batch/TPCHQuery10.py
/usr/share/flink/examples/python/batch/TPCHQuery3.py
/usr/share/flink/examples/python/batch/TriangleEnumeration.py
/usr/share/flink/examples/python/batch/WebLogAnalysis.py
/usr/share/flink/examples/python/batch/WordCount.py
/usr/share/flink/examples/python/batch/__init__.py
/usr/share/flink/examples/python/streaming/fibonacci.py
/usr/share/flink/examples/python/streaming/word_count.py
/usr/share/flink/examples/streaming/IncrementalLearning.jar
/usr/share/flink/examples/streaming/Iteration.jar
/usr/share/flink/examples/streaming/SessionWindowing.jar
/usr/share/flink/examples/streaming/SocketWindowWordCount.jar
/usr/share/flink/examples/streaming/StateMachineExample.jar
/usr/share/flink/examples/streaming/TopSpeedWindowing.jar
/usr/share/flink/examples/streaming/Twitter.jar
/usr/share/flink/examples/streaming/WindowJoin.jar
/usr/share/flink/examples/streaming/WordCount.jar
/usr/share/flink/lib/flink-dist_2.11-1.7.2.jar
/usr/share/flink/lib/flink-python_2.11-1.7.2.jar
/usr/share/flink/lib/flink-shaded-hadoop2-uber-1.7.2.jar
/usr/share/flink/lib/log4j-1.2.17.jar
/usr/share/flink/lib/slf4j-log4j12-1.7.15.jar
/usr/share/flink/opt/flink-cep-scala_2.11-1.7.2.jar
/usr/share/flink/opt/flink-cep_2.11-1.7.2.jar
/usr/share/flink/opt/flink-gelly-scala_2.11-1.7.2.jar
/usr/share/flink/opt/flink-gelly_2.11-1.7.2.jar
/usr/share/flink/opt/flink-metrics-datadog-1.7.2.jar
/usr/share/flink/opt/flink-metrics-graphite-1.7.2.jar
/usr/share/flink/opt/flink-metrics-prometheus-1.7.2.jar
/usr/share/flink/opt/flink-metrics-slf4j-1.7.2.jar
/usr/share/flink/opt/flink-metrics-statsd-1.7.2.jar
/usr/share/flink/opt/flink-ml_2.11-1.7.2.jar
/usr/share/flink/opt/flink-queryable-state-runtime_2.11-1.7.2.jar
/usr/share/flink/opt/flink-s3-fs-hadoop-1.7.2.jar
/usr/share/flink/opt/flink-s3-fs-presto-1.7.2.jar
/usr/share/flink/opt/flink-sql-client_2.11-1.7.2.jar
/usr/share/flink/opt/flink-streaming-python_2.11-1.7.2.jar
/usr/share/flink/opt/flink-swift-fs-hadoop-1.7.2.jar
/usr/share/flink/opt/flink-table_2.11-1.7.2.jar

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/flink/LICENSE
/usr/share/doc/flink/NOTICE
/usr/share/doc/flink/README.txt
/usr/share/doc/flink/licenses/LICENSE-hdrhistogram
/usr/share/doc/flink/licenses/LICENSE-protobuf
/usr/share/doc/flink/licenses/LICENSE-re2j
/usr/share/doc/flink/licenses/LICENSE-stax2api
/usr/share/doc/flink/licenses/LICENSE-xmlenc
/usr/share/doc/flink/licenses/LICENSE.angular
/usr/share/doc/flink/licenses/LICENSE.angular-drag-and-drop-list
/usr/share/doc/flink/licenses/LICENSE.angular-moment
/usr/share/doc/flink/licenses/LICENSE.angular-ui-router
/usr/share/doc/flink/licenses/LICENSE.arpack_combined_all
/usr/share/doc/flink/licenses/LICENSE.asm.txt
/usr/share/doc/flink/licenses/LICENSE.base64
/usr/share/doc/flink/licenses/LICENSE.bootstrap
/usr/share/doc/flink/licenses/LICENSE.cddlv1.0
/usr/share/doc/flink/licenses/LICENSE.cddlv1.1
/usr/share/doc/flink/licenses/LICENSE.core
/usr/share/doc/flink/licenses/LICENSE.d3
/usr/share/doc/flink/licenses/LICENSE.dagre
/usr/share/doc/flink/licenses/LICENSE.dagre-d3
/usr/share/doc/flink/licenses/LICENSE.ev-emitter
/usr/share/doc/flink/licenses/LICENSE.font-awesome
/usr/share/doc/flink/licenses/LICENSE.graphlib
/usr/share/doc/flink/licenses/LICENSE.grizzled-slf4j
/usr/share/doc/flink/licenses/LICENSE.imagesloaded
/usr/share/doc/flink/licenses/LICENSE.janino
/usr/share/doc/flink/licenses/LICENSE.jline
/usr/share/doc/flink/licenses/LICENSE.jquery
/usr/share/doc/flink/licenses/LICENSE.jsch
/usr/share/doc/flink/licenses/LICENSE.jsr166y
/usr/share/doc/flink/licenses/LICENSE.jtransforms
/usr/share/doc/flink/licenses/LICENSE.jython
/usr/share/doc/flink/licenses/LICENSE.jzlib
/usr/share/doc/flink/licenses/LICENSE.kryo
/usr/share/doc/flink/licenses/LICENSE.lodash
/usr/share/doc/flink/licenses/LICENSE.machinist
/usr/share/doc/flink/licenses/LICENSE.minlog
/usr/share/doc/flink/licenses/LICENSE.moment
/usr/share/doc/flink/licenses/LICENSE.moment-duration-format
/usr/share/doc/flink/licenses/LICENSE.paranamer
/usr/share/doc/flink/licenses/LICENSE.protobuf
/usr/share/doc/flink/licenses/LICENSE.qtip2
/usr/share/doc/flink/licenses/LICENSE.scala
/usr/share/doc/flink/licenses/LICENSE.scopt
/usr/share/doc/flink/licenses/LICENSE.slf4j
/usr/share/doc/flink/licenses/LICENSE.slf4j-api
/usr/share/doc/flink/licenses/LICENSE.spire
/usr/share/doc/flink/licenses/LICENSE.split
/usr/share/doc/flink/licenses/LICENSE.webbit
/usr/share/doc/flink/licenses/LICENSE.xmlenc
