#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : apache-flink
Version  : 1.8.1
Release  : 5
URL      : https://github.com/apache/flink/archive/release-1.8.1.tar.gz
Source0  : https://github.com/apache/flink/archive/release-1.8.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-2-Clause-FreeBSD BSD-3-Clause BSD-3-Clause-Clear CC-BY-2.5 CC-BY-3.0 CC0-1.0 CDDL-1.0 CDDL-1.1 EPL-1.0 LGPL-2.1 MIT MPL-1.1 MPL-2.0-no-copyleft-exception OFL-1.1 Public-Domain Python-2.0 Saxpath W3C
Requires: apache-flink-data = %{version}-%{release}
Requires: openjdk
BuildRequires : apache-maven
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-mvn
BuildRequires : cmake
BuildRequires : mvn-Fenzo
BuildRequires : mvn-HdrHistogram
BuildRequires : mvn-JavaEWAH
BuildRequires : mvn-JsonPath
BuildRequires : mvn-accessors-smart
BuildRequires : mvn-activation
BuildRequires : mvn-addthis-oss-jar-pom
BuildRequires : mvn-aether-core
BuildRequires : mvn-aggdesigner
BuildRequires : mvn-airbase
BuildRequires : mvn-aircompressor
BuildRequires : mvn-airlift
BuildRequires : mvn-airlift-slice
BuildRequires : mvn-airlift-units
BuildRequires : mvn-akka
BuildRequires : mvn-aliyun-openapi-java-sdk
BuildRequires : mvn-aliyun-oss-java-sdk
BuildRequires : mvn-animal-sniffer
BuildRequires : mvn-ant
BuildRequires : mvn-ant-launcher
BuildRequires : mvn-antlr
BuildRequires : mvn-antlr4
BuildRequires : mvn-aopalliance
BuildRequires : mvn-apache
BuildRequires : mvn-apache-jar-resource-bundle
BuildRequires : mvn-archetype
BuildRequires : mvn-arpack_combined_all
BuildRequires : mvn-asm
BuildRequires : mvn-autolink
BuildRequires : mvn-avalon-framework
BuildRequires : mvn-avro
BuildRequires : mvn-aws-java-sdk
BuildRequires : mvn-backport-util-concurrent
BuildRequires : mvn-beanshell
BuildRequires : mvn-biz.aQute.bndlib
BuildRequires : mvn-bndlib
BuildRequires : mvn-bonecp
BuildRequires : mvn-bouncycastle
BuildRequires : mvn-breeze-macros_2.11
BuildRequires : mvn-breeze_2.11
BuildRequires : mvn-breeze_2.12
BuildRequires : mvn-build-helper-maven-plugin
BuildRequires : mvn-byte-buddy
BuildRequires : mvn-calcite
BuildRequires : mvn-calcite-avatica
BuildRequires : mvn-camel
BuildRequires : mvn-cassandra
BuildRequires : mvn-cdi-api
BuildRequires : mvn-checkerframework
BuildRequires : mvn-checkstyle
BuildRequires : mvn-chill-java
BuildRequires : mvn-chill_2.12
BuildRequires : mvn-classutil_2.12
BuildRequires : mvn-classworlds
BuildRequires : mvn-client_java
BuildRequires : mvn-codehaus-jackson
BuildRequires : mvn-common
BuildRequires : mvn-commons-beanutils
BuildRequires : mvn-commons-chain
BuildRequires : mvn-commons-cli
BuildRequires : mvn-commons-codec
BuildRequires : mvn-commons-collections
BuildRequires : mvn-commons-compress
BuildRequires : mvn-commons-configuration
BuildRequires : mvn-commons-configuration2
BuildRequires : mvn-commons-daemon
BuildRequires : mvn-commons-dbcp
BuildRequires : mvn-commons-digester
BuildRequires : mvn-commons-el
BuildRequires : mvn-commons-exec
BuildRequires : mvn-commons-httpclient
BuildRequires : mvn-commons-io
BuildRequires : mvn-commons-lang
BuildRequires : mvn-commons-lang3
BuildRequires : mvn-commons-logging
BuildRequires : mvn-commons-math
BuildRequires : mvn-commons-math3
BuildRequires : mvn-commons-net
BuildRequires : mvn-commons-parent
BuildRequires : mvn-commons-pool
BuildRequires : mvn-commons-validator
BuildRequires : mvn-compiler-interface
BuildRequires : mvn-compress-lzf
BuildRequires : mvn-concurrentlinkedhashmap
BuildRequires : mvn-config
BuildRequires : mvn-crc32ex
BuildRequires : mvn-curator
BuildRequires : mvn-datanucleus-api-jdo
BuildRequires : mvn-datanucleus-core
BuildRequires : mvn-datanucleus-rdbms
BuildRequires : mvn-derby
BuildRequires : mvn-directory-jdbm
BuildRequires : mvn-directory-ldap-api
BuildRequires : mvn-directory-maven-plugin
BuildRequires : mvn-directory-mavibot
BuildRequires : mvn-directory-project
BuildRequires : mvn-directory-server
BuildRequires : mvn-disruptor
BuildRequires : mvn-disruptor_thrift_server
BuildRequires : mvn-dom4j
BuildRequires : mvn-doxia
BuildRequires : mvn-doxia-sitetools
BuildRequires : mvn-doxia-tools
BuildRequires : mvn-droolsjbpm-build-bootstrap
BuildRequires : mvn-easymock
BuildRequires : mvn-ehcache
BuildRequires : mvn-elasticsearch
BuildRequires : mvn-enforcer
BuildRequires : mvn-error_prone_annotations
BuildRequires : mvn-exec-maven-plugin
BuildRequires : mvn-ezmorph
BuildRequires : mvn-fastutil
BuildRequires : mvn-felix
BuildRequires : mvn-file-management
BuildRequires : mvn-findbugs-annotations
BuildRequires : mvn-flexmark-java
BuildRequires : mvn-flink-shaded
BuildRequires : mvn-frocksdb
BuildRequires : mvn-genesis
BuildRequires : mvn-geronimo-jcache_1.0_spec
BuildRequires : mvn-google
BuildRequires : mvn-google-collections
BuildRequires : mvn-grizzled-scala_2.12
BuildRequires : mvn-grizzled-slf4j_2.11
BuildRequires : mvn-grizzled-slf4j_2.12
BuildRequires : mvn-groovy
BuildRequires : mvn-gson
BuildRequires : mvn-guava
BuildRequires : mvn-guice
BuildRequires : mvn-guice-servlet
BuildRequires : mvn-hadoop
BuildRequires : mvn-hadoop-aliyun
BuildRequires : mvn-hamcrest
BuildRequires : mvn-handlebars.java
BuildRequires : mvn-hbase
BuildRequires : mvn-hbc
BuildRequires : mvn-hibernate-validator
BuildRequires : mvn-high-scale-lib
BuildRequires : mvn-hive
BuildRequires : mvn-hppc
BuildRequires : mvn-htrace
BuildRequires : mvn-httpcomponents-client
BuildRequires : mvn-httpcomponents-core
BuildRequires : mvn-icu4j
BuildRequires : mvn-incremental-compiler
BuildRequires : mvn-incubator-datasketches-java
BuildRequires : mvn-influxdb-java
BuildRequires : mvn-intellij.annotations
BuildRequires : mvn-ion-java
BuildRequires : mvn-irclib
BuildRequires : mvn-j2objc-annotations
BuildRequires : mvn-jBCrypt
BuildRequires : mvn-jackson-annotations
BuildRequires : mvn-jackson-bom
BuildRequires : mvn-jackson-core
BuildRequires : mvn-jackson-databind
BuildRequires : mvn-jackson-dataformat-cbor
BuildRequires : mvn-jackson-dataformat-smile
BuildRequires : mvn-jackson-dataformat-yaml
BuildRequires : mvn-jackson-dataformats-binary
BuildRequires : mvn-jackson-module-scala_2.11
BuildRequires : mvn-jackson-module-scala_2.12
BuildRequires : mvn-jackson-parent
BuildRequires : mvn-jamm
BuildRequires : mvn-jamon-java-parent
BuildRequires : mvn-jamon-parent
BuildRequires : mvn-jamon-runtime
BuildRequires : mvn-janino
BuildRequires : mvn-java-xmlbuilder
BuildRequires : mvn-javassist
BuildRequires : mvn-javax-servlet
BuildRequires : mvn-javax.inject
BuildRequires : mvn-javax.servlet-api
BuildRequires : mvn-javax.ws.rs-api
BuildRequires : mvn-javolution
BuildRequires : mvn-jaxb-api
BuildRequires : mvn-jaxb-impl
BuildRequires : mvn-jboss-logging
BuildRequires : mvn-jboss-parent
BuildRequires : mvn-jchardet
BuildRequires : mvn-jcip-annotations
BuildRequires : mvn-jcodings
BuildRequires : mvn-jdependency
BuildRequires : mvn-jdo-api
BuildRequires : mvn-jdom
BuildRequires : mvn-jersey
BuildRequires : mvn-jets3t
BuildRequires : mvn-jettison
BuildRequires : mvn-jetty
BuildRequires : mvn-jetty-parent
BuildRequires : mvn-jgit
BuildRequires : mvn-jline
BuildRequires : mvn-jmxutils
BuildRequires : mvn-jna
BuildRequires : mvn-joauth
BuildRequires : mvn-joda-convert
BuildRequires : mvn-joda-time
BuildRequires : mvn-joni
BuildRequires : mvn-jopt-simple
BuildRequires : mvn-jsch
BuildRequires : mvn-json
BuildRequires : mvn-json-lib
BuildRequires : mvn-json-simple
BuildRequires : mvn-json-smart
BuildRequires : mvn-json4s
BuildRequires : mvn-jsoup
BuildRequires : mvn-jsp-api
BuildRequires : mvn-jsr166e
BuildRequires : mvn-jsr305
BuildRequires : mvn-jsr311
BuildRequires : mvn-jta
BuildRequires : mvn-jtidy
BuildRequires : mvn-jtransforms
BuildRequires : mvn-junit
BuildRequires : mvn-jython-standalone
BuildRequires : mvn-kafka-clients
BuildRequires : mvn-kafka_2.11
BuildRequires : mvn-kafka_2.12
BuildRequires : mvn-kerby
BuildRequires : mvn-kryo
BuildRequires : mvn-kxml2
BuildRequires : mvn-leveldbjni
BuildRequires : mvn-log4j
BuildRequires : mvn-logback-core
BuildRequires : mvn-logging-log4j2
BuildRequires : mvn-logging-parent
BuildRequires : mvn-logkit
BuildRequires : mvn-lombok
BuildRequires : mvn-lucene-solr
BuildRequires : mvn-lz4-java
BuildRequires : mvn-machinist_2.11
BuildRequires : mvn-machinist_2.12
BuildRequires : mvn-macro-compat_2.11
BuildRequires : mvn-macro-compat_2.12
BuildRequires : mvn-mapr-hadoop
BuildRequires : mvn-maprfs
BuildRequires : mvn-maven
BuildRequires : mvn-maven-aether-provider
BuildRequires : mvn-maven-antrun-plugin
BuildRequires : mvn-maven-archetype
BuildRequires : mvn-maven-archiver
BuildRequires : mvn-maven-artifact
BuildRequires : mvn-maven-artifact-manager
BuildRequires : mvn-maven-artifact-transfer
BuildRequires : mvn-maven-assembly-plugin
BuildRequires : mvn-maven-bundle-plugin
BuildRequires : mvn-maven-checkstyle-plugin
BuildRequires : mvn-maven-clean-plugin
BuildRequires : mvn-maven-common-artifact-filters
BuildRequires : mvn-maven-compat
BuildRequires : mvn-maven-compiler-plugin
BuildRequires : mvn-maven-core
BuildRequires : mvn-maven-dependency-plugin
BuildRequires : mvn-maven-error-diagnostics
BuildRequires : mvn-maven-filtering
BuildRequires : mvn-maven-git-commit-id-plugin
BuildRequires : mvn-maven-invoker
BuildRequires : mvn-maven-jar-plugin
BuildRequires : mvn-maven-model
BuildRequires : mvn-maven-model-builder
BuildRequires : mvn-maven-monitor
BuildRequires : mvn-maven-parent
BuildRequires : mvn-maven-plugin-api
BuildRequires : mvn-maven-plugin-descriptor
BuildRequires : mvn-maven-plugin-parameter-documenter
BuildRequires : mvn-maven-plugin-registry
BuildRequires : mvn-maven-plugin-tools
BuildRequires : mvn-maven-plugins
BuildRequires : mvn-maven-profile
BuildRequires : mvn-maven-project
BuildRequires : mvn-maven-reporting-api
BuildRequires : mvn-maven-reporting-exec
BuildRequires : mvn-maven-reporting-impl
BuildRequires : mvn-maven-repository-builder
BuildRequires : mvn-maven-repository-metadata
BuildRequires : mvn-maven-resources-plugin
BuildRequires : mvn-maven-script-interpreter
BuildRequires : mvn-maven-settings
BuildRequires : mvn-maven-settings-builder
BuildRequires : mvn-maven-shade-plugin
BuildRequires : mvn-maven-shared
BuildRequires : mvn-maven-shared-utils
BuildRequires : mvn-maven-site-plugin
BuildRequires : mvn-maven-source-plugin
BuildRequires : mvn-maven-surefire
BuildRequires : mvn-maven-toolchain
BuildRequires : mvn-mesos
BuildRequires : mvn-metrics
BuildRequires : mvn-metrics-reporter-config
BuildRequires : mvn-mina
BuildRequires : mvn-minlog
BuildRequires : mvn-mockito
BuildRequires : mvn-mockito-core
BuildRequires : mvn-mojo-parent
BuildRequires : mvn-moshi
BuildRequires : mvn-msgpack-java
BuildRequires : mvn-mustache.java
BuildRequires : mvn-mvnplugins
BuildRequires : mvn-netlib-java
BuildRequires : mvn-netty
BuildRequires : mvn-nifi
BuildRequires : mvn-nifi-registry
BuildRequires : mvn-nimbus-jose-jwt
BuildRequires : mvn-objenesis
BuildRequires : mvn-okhttp
BuildRequires : mvn-okio
BuildRequires : mvn-opencsv
BuildRequires : mvn-openhtmltopdf-parent
BuildRequires : mvn-orc
BuildRequires : mvn-org.apache.felix.bundlerepository
BuildRequires : mvn-org.osgi.compendium
BuildRequires : mvn-org.osgi.core
BuildRequires : mvn-oro
BuildRequires : mvn-oshi
BuildRequires : mvn-oss-parents
BuildRequires : mvn-ow2
BuildRequires : mvn-paradise
BuildRequires : mvn-paranamer
BuildRequires : mvn-parboiled
BuildRequires : mvn-parquet-format
BuildRequires : mvn-parquet-mr
BuildRequires : mvn-pdfbox
BuildRequires : mvn-pegdown
BuildRequires : mvn-plexus
BuildRequires : mvn-plexus-archiver
BuildRequires : mvn-plexus-build-api
BuildRequires : mvn-plexus-cipher
BuildRequires : mvn-plexus-classworlds
BuildRequires : mvn-plexus-compiler
BuildRequires : mvn-plexus-containers
BuildRequires : mvn-plexus-i18n
BuildRequires : mvn-plexus-interactivity
BuildRequires : mvn-plexus-interpolation
BuildRequires : mvn-plexus-io
BuildRequires : mvn-plexus-languages
BuildRequires : mvn-plexus-resources
BuildRequires : mvn-plexus-utils
BuildRequires : mvn-plexus-velocity
BuildRequires : mvn-powermock
BuildRequires : mvn-presto
BuildRequires : mvn-protobuf-java
BuildRequires : mvn-qdox
BuildRequires : mvn-rabbitmq
BuildRequires : mvn-re2j
BuildRequires : mvn-reactivestreams
BuildRequires : mvn-reflections
BuildRequires : mvn-retrofit
BuildRequires : mvn-rhino
BuildRequires : mvn-saxon
BuildRequires : mvn-sbt-interface
BuildRequires : mvn-scala-compiler
BuildRequires : mvn-scala-java8-compat
BuildRequires : mvn-scala-library
BuildRequires : mvn-scala-logging
BuildRequires : mvn-scala-maven-plugin
BuildRequires : mvn-scala-parser-combinators_2.11
BuildRequires : mvn-scala-parser-combinators_2.12
BuildRequires : mvn-scala-reflect
BuildRequires : mvn-scala-xml_2.11
BuildRequires : mvn-scala-xml_2.12
BuildRequires : mvn-scalacheck
BuildRequires : mvn-scalactic_2.11
BuildRequires : mvn-scalactic_2.12
BuildRequires : mvn-scalastyle-maven-plugin
BuildRequires : mvn-scalatest-maven-plugin
BuildRequires : mvn-scalatest_2.11
BuildRequires : mvn-scalatest_2.12
BuildRequires : mvn-schema-registry
BuildRequires : mvn-scopt_2.11
BuildRequires : mvn-scopt_2.12
BuildRequires : mvn-servlet-api
BuildRequires : mvn-shapeless_2.11
BuildRequires : mvn-shapeless_2.12
BuildRequires : mvn-sigar
BuildRequires : mvn-sisu
BuildRequires : mvn-sisu-guice
BuildRequires : mvn-slf4j
BuildRequires : mvn-snakeyaml
BuildRequires : mvn-snappy
BuildRequires : mvn-snappy-java
BuildRequires : mvn-sonatype-aether
BuildRequires : mvn-sonatype-plexus-sec-dispatcher
BuildRequires : mvn-spatial4j
BuildRequires : mvn-spire_2.11
BuildRequires : mvn-spire_2.12
BuildRequires : mvn-ssl-config
BuildRequires : mvn-sslext
BuildRequires : mvn-stax-api
BuildRequires : mvn-stax2-api
BuildRequires : mvn-stream-lib
BuildRequires : mvn-stringtemplate
BuildRequires : mvn-stringtemplate4
BuildRequires : mvn-struts
BuildRequires : mvn-super-csv
BuildRequires : mvn-swagger-core
BuildRequires : mvn-t-digest
BuildRequires : mvn-thrift
BuildRequires : mvn-tomcat
BuildRequires : mvn-tycho
BuildRequires : mvn-uncommons-maths
BuildRequires : mvn-unirest-java
BuildRequires : mvn-validation-api
BuildRequires : mvn-velocity
BuildRequires : mvn-velocity-tools
BuildRequires : mvn-wagon
BuildRequires : mvn-wiremock
BuildRequires : mvn-woodstox-core
BuildRequires : mvn-xalan
BuildRequires : mvn-xbean
BuildRequires : mvn-xercesImpl
BuildRequires : mvn-xml-apis
BuildRequires : mvn-xmlenc
BuildRequires : mvn-xmlpull
BuildRequires : mvn-xmlunit
BuildRequires : mvn-xmlunit-core
BuildRequires : mvn-xpp3_min
BuildRequires : mvn-xz
BuildRequires : mvn-zinc
BuildRequires : mvn-zjsonpatch
BuildRequires : mvn-zkclient
BuildRequires : mvn-zookeeper
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openssl-dev
BuildRequires : zlib-dev
Patch1: 0001-Stateless.patch

%description
# Apache Flink
Apache Flink is an open source stream processing framework with powerful stream- and batch-processing capabilities.

%package data
Summary: data components for the apache-flink package.
Group: Data

%description data
data components for the apache-flink package.


%package doc
Summary: doc components for the apache-flink package.
Group: Documentation

%description doc
doc components for the apache-flink package.


%prep
%setup -q -n flink-release-1.8.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
mkdir -p %{buildroot}
cp -r /usr/share/java/.m2 ~/.m2 || :
mvn --offline package -o -Pnative -Pdist -DskipTests -Dtar -Dscala-2.12

%install

mkdir -p %{buildroot}/usr/share/package-licenses/apache-flink
cp LICENSE %{buildroot}/usr/share/package-licenses/apache-flink/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/NOTICE
cp docs/fig/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-flink/docs_fig_LICENSE.txt
cp docs/page/img/LICENSE.txt %{buildroot}/usr/share/package-licenses/apache-flink/docs_page_img_LICENSE.txt
cp flink-connectors/flink-connector-cassandra/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-cassandra_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-connector-elasticsearch/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-connector-elasticsearch/src/main/resources/META-INF/licenses/LICENSE.antlr %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch_src_main_resources_META-INF_licenses_LICENSE.antlr
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/licenses/LICENSE.base64 %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_licenses_LICENSE.base64
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/licenses/LICENSE.hdrhistogram %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_licenses_LICENSE.hdrhistogram
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/licenses/LICENSE.jsr166e %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_licenses_LICENSE.jsr166e
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/licenses/LICENSE.jsr166y %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_licenses_LICENSE.jsr166y
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/licenses/LICENSE.jzlib %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_licenses_LICENSE.jzlib
cp flink-connectors/flink-connector-elasticsearch2/src/main/resources/META-INF/licenses/LICENSE.webbit %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch2_src_main_resources_META-INF_licenses_LICENSE.webbit
cp flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/licenses/LICENSE.base64 %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch5_src_main_resources_META-INF_licenses_LICENSE.base64
cp flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/licenses/LICENSE.hdrhistogram %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch5_src_main_resources_META-INF_licenses_LICENSE.hdrhistogram
cp flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/licenses/LICENSE.joptsimple %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch5_src_main_resources_META-INF_licenses_LICENSE.joptsimple
cp flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/licenses/LICENSE.jsr166y %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch5_src_main_resources_META-INF_licenses_LICENSE.jsr166y
cp flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/licenses/LICENSE.jzlib %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch5_src_main_resources_META-INF_licenses_LICENSE.jzlib
cp flink-connectors/flink-connector-elasticsearch5/src/main/resources/META-INF/licenses/LICENSE.webbit %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-elasticsearch5_src_main_resources_META-INF_licenses_LICENSE.webbit
cp flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-kinesis_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/licenses/LICENSE.amazon %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-kinesis_src_main_resources_META-INF_licenses_LICENSE.amazon
cp flink-connectors/flink-connector-kinesis/src/main/resources/META-INF/licenses/LICENSE.protobuf %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-kinesis_src_main_resources_META-INF_licenses_LICENSE.protobuf
cp flink-connectors/flink-connector-twitter/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-connector-twitter_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-sql-connector-elasticsearch6/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-sql-connector-elasticsearch6_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-sql-connector-kafka-0.10/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-sql-connector-kafka-0.10_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-sql-connector-kafka-0.11/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-sql-connector-kafka-0.11_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-sql-connector-kafka-0.9/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-sql-connector-kafka-0.9_src_main_resources_META-INF_NOTICE
cp flink-connectors/flink-sql-connector-kafka/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-connectors_flink-sql-connector-kafka_src_main_resources_META-INF_NOTICE
cp flink-core/src/main/java/org/apache/flink/api/common/functions/util/CopyingIterator.java %{buildroot}/usr/share/package-licenses/apache-flink/flink-core_src_main_java_org_apache_flink_api_common_functions_util_CopyingIterator.java
cp flink-core/src/main/java/org/apache/flink/api/common/functions/util/CopyingListCollector.java %{buildroot}/usr/share/package-licenses/apache-flink/flink-core_src_main_java_org_apache_flink_api_common_functions_util_CopyingListCollector.java
cp flink-dist/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_NOTICE
cp flink-dist/src/main/resources/META-INF/licenses/LICENSE.grizzled-slf4j %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_licenses_LICENSE.grizzled-slf4j
cp flink-dist/src/main/resources/META-INF/licenses/LICENSE.kryo %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_licenses_LICENSE.kryo
cp flink-dist/src/main/resources/META-INF/licenses/LICENSE.minlog %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_licenses_LICENSE.minlog
cp flink-dist/src/main/resources/META-INF/licenses/LICENSE.scala %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_licenses_LICENSE.scala
cp flink-dist/src/main/resources/META-INF/licenses/LICENSE.scopt %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_licenses_LICENSE.scopt
cp flink-dist/src/main/resources/META-INF/licenses/LICENSE.slf4j-api %{buildroot}/usr/share/package-licenses/apache-flink/flink-dist_src_main_resources_META-INF_licenses_LICENSE.slf4j-api
cp flink-examples/flink-examples-build-helper/flink-examples-streaming-state-machine/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-examples_flink-examples-build-helper_flink-examples-streaming-state-machine_src_main_resources_META-INF_NOTICE
cp flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-fs-hadoop-shaded_src_main_resources_META-INF_NOTICE
cp flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/licenses/LICENSE-re2j %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-fs-hadoop-shaded_src_main_resources_META-INF_licenses_LICENSE-re2j
cp flink-filesystems/flink-fs-hadoop-shaded/src/main/resources/META-INF/licenses/LICENSE-stax2api %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-fs-hadoop-shaded_src_main_resources_META-INF_licenses_LICENSE-stax2api
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_NOTICE
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.asm %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.asm
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.cddlv1.0 %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.cddlv1.0
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.cddlv1.1 %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.cddlv1.1
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.jdom %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.jdom
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.jzlib %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.jzlib
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.paranamer %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.paranamer
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.protobuf %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.protobuf
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.re2j %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.re2j
cp flink-filesystems/flink-oss-fs-hadoop/src/main/resources/licenses/LICENSE.stax2api %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-oss-fs-hadoop_src_main_resources_licenses_LICENSE.stax2api
cp flink-filesystems/flink-s3-fs-base/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-s3-fs-base_src_main_resources_META-INF_NOTICE
cp flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-s3-fs-presto_src_main_resources_META-INF_NOTICE
cp flink-filesystems/flink-s3-fs-presto/src/main/resources/META-INF/licenses/LICENSE-hdrhistogram %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-s3-fs-presto_src_main_resources_META-INF_licenses_LICENSE-hdrhistogram
cp flink-filesystems/flink-swift-fs-hadoop/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-swift-fs-hadoop_src_main_resources_META-INF_NOTICE
cp flink-filesystems/flink-swift-fs-hadoop/src/main/resources/META-INF/licenses/LICENSE-protobuf %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-swift-fs-hadoop_src_main_resources_META-INF_licenses_LICENSE-protobuf
cp flink-filesystems/flink-swift-fs-hadoop/src/main/resources/META-INF/licenses/LICENSE-xmlenc %{buildroot}/usr/share/package-licenses/apache-flink/flink-filesystems_flink-swift-fs-hadoop_src_main_resources_META-INF_licenses_LICENSE-xmlenc
cp flink-formats/flink-avro-confluent-registry/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-formats_flink-avro-confluent-registry_src_main_resources_META-INF_NOTICE
cp flink-libraries/flink-ml-uber/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-ml-uber_src_main_resources_META-INF_NOTICE
cp flink-libraries/flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.arpack_combined_all %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-ml-uber_src_main_resources_META-INF_licenses_LICENSE.arpack_combined_all
cp flink-libraries/flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.core %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-ml-uber_src_main_resources_META-INF_licenses_LICENSE.core
cp flink-libraries/flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.jtransforms %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-ml-uber_src_main_resources_META-INF_licenses_LICENSE.jtransforms
cp flink-libraries/flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.machinist %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-ml-uber_src_main_resources_META-INF_licenses_LICENSE.machinist
cp flink-libraries/flink-ml-uber/src/main/resources/META-INF/licenses/LICENSE.spire %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-ml-uber_src_main_resources_META-INF_licenses_LICENSE.spire
cp flink-libraries/flink-streaming-python/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-streaming-python_src_main_resources_META-INF_NOTICE
cp flink-libraries/flink-streaming-python/src/main/resources/META-INF/licenses/LICENSE.jython %{buildroot}/usr/share/package-licenses/apache-flink/flink-libraries_flink-streaming-python_src_main_resources_META-INF_licenses_LICENSE.jython
cp flink-mesos/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-mesos_src_main_resources_META-INF_NOTICE
cp flink-mesos/src/main/resources/META-INF/licenses/LICENSE.protobuf %{buildroot}/usr/share/package-licenses/apache-flink/flink-mesos_src_main_resources_META-INF_licenses_LICENSE.protobuf
cp flink-metrics/flink-metrics-datadog/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-metrics_flink-metrics-datadog_src_main_resources_META-INF_NOTICE
cp flink-metrics/flink-metrics-graphite/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-metrics_flink-metrics-graphite_src_main_resources_META-INF_NOTICE
cp flink-metrics/flink-metrics-influxdb/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-metrics_flink-metrics-influxdb_src_main_resources_META-INF_NOTICE
cp flink-metrics/flink-metrics-influxdb/src/main/resources/META-INF/licenses/LICENSE.influx %{buildroot}/usr/share/package-licenses/apache-flink/flink-metrics_flink-metrics-influxdb_src_main_resources_META-INF_licenses_LICENSE.influx
cp flink-metrics/flink-metrics-prometheus/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-metrics_flink-metrics-prometheus_src_main_resources_META-INF_NOTICE
cp flink-runtime-web/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_NOTICE
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.angular %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.angular
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.angular-drag-and-drop-list %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.angular-drag-and-drop-list
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.angular-moment %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.angular-moment
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.angular-ui-router %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.angular-ui-router
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.bootstrap %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.bootstrap
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.d3 %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.d3
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.dagre %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.dagre
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.dagre-d3 %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.dagre-d3
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.ev-emitter %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.ev-emitter
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.font-awesome %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.font-awesome
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.graphlib %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.graphlib
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.imagesloaded %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.imagesloaded
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.jquery %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.jquery
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.lodash %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.lodash
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.moment %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.moment
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.moment-duration-format %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.moment-duration-format
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.qtip2 %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.qtip2
cp flink-runtime-web/src/main/resources/META-INF/licenses/LICENSE.split %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime-web_src_main_resources_META-INF_licenses_LICENSE.split
cp flink-runtime/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime_src_main_resources_META-INF_NOTICE
cp flink-runtime/src/main/resources/META-INF/licenses/LICENSE.base64 %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime_src_main_resources_META-INF_licenses_LICENSE.base64
cp flink-runtime/src/main/resources/META-INF/licenses/LICENSE.jsr166y %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime_src_main_resources_META-INF_licenses_LICENSE.jsr166y
cp flink-runtime/src/main/resources/META-INF/licenses/LICENSE.jzlib %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime_src_main_resources_META-INF_licenses_LICENSE.jzlib
cp flink-runtime/src/main/resources/META-INF/licenses/LICENSE.webbit %{buildroot}/usr/share/package-licenses/apache-flink/flink-runtime_src_main_resources_META-INF_licenses_LICENSE.webbit
cp flink-shaded-curator/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-curator_src_main_resources_META-INF_NOTICE
cp flink-shaded-hadoop/flink-shaded-hadoop2-uber/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2-uber_src_main_resources_META-INF_NOTICE
cp flink-shaded-hadoop/flink-shaded-hadoop2-uber/src/main/resources/META-INF/licenses/LICENSE.cddlv1.0 %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2-uber_src_main_resources_META-INF_licenses_LICENSE.cddlv1.0
cp flink-shaded-hadoop/flink-shaded-hadoop2-uber/src/main/resources/META-INF/licenses/LICENSE.cddlv1.1 %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2-uber_src_main_resources_META-INF_licenses_LICENSE.cddlv1.1
cp flink-shaded-hadoop/flink-shaded-hadoop2-uber/src/main/resources/META-INF/licenses/LICENSE.jsch %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2-uber_src_main_resources_META-INF_licenses_LICENSE.jsch
cp flink-shaded-hadoop/flink-shaded-hadoop2-uber/src/main/resources/META-INF/licenses/LICENSE.paranamer %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2-uber_src_main_resources_META-INF_licenses_LICENSE.paranamer
cp flink-shaded-hadoop/flink-shaded-hadoop2-uber/src/main/resources/META-INF/licenses/LICENSE.xmlenc %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2-uber_src_main_resources_META-INF_licenses_LICENSE.xmlenc
cp flink-shaded-hadoop/flink-shaded-hadoop2/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2_src_main_resources_META-INF_NOTICE
cp flink-shaded-hadoop/flink-shaded-hadoop2/src/main/resources/META-INF/licenses/LICENSE.protobuf %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-hadoop2_src_main_resources_META-INF_licenses_LICENSE.protobuf
cp flink-shaded-hadoop/flink-shaded-yarn-tests/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-yarn-tests_src_main_resources_META-INF_NOTICE
cp flink-shaded-hadoop/flink-shaded-yarn-tests/src/main/resources/META-INF/licenses/LICENSE.asm %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-yarn-tests_src_main_resources_META-INF_licenses_LICENSE.asm
cp flink-shaded-hadoop/flink-shaded-yarn-tests/src/main/resources/META-INF/licenses/LICENSE.protobuf %{buildroot}/usr/share/package-licenses/apache-flink/flink-shaded-hadoop_flink-shaded-yarn-tests_src_main_resources_META-INF_licenses_LICENSE.protobuf
cp flink-streaming-java/src/main/java/org/apache/flink/streaming/api/collector/selector/CopyingDirectedOutput.java %{buildroot}/usr/share/package-licenses/apache-flink/flink-streaming-java_src_main_java_org_apache_flink_streaming_api_collector_selector_CopyingDirectedOutput.java
cp flink-table/flink-sql-client/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-table_flink-sql-client_src_main_resources_META-INF_NOTICE
cp flink-table/flink-sql-client/src/main/resources/META-INF/licenses/LICENSE.jline %{buildroot}/usr/share/package-licenses/apache-flink/flink-table_flink-sql-client_src_main_resources_META-INF_licenses_LICENSE.jline
cp flink-table/flink-table-planner/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-table_flink-table-planner_src_main_resources_META-INF_NOTICE
cp flink-table/flink-table-planner/src/main/resources/META-INF/licenses/LICENSE.janino %{buildroot}/usr/share/package-licenses/apache-flink/flink-table_flink-table-planner_src_main_resources_META-INF_licenses_LICENSE.janino
cp flink-test-utils-parent/flink-test-utils/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/apache-flink/flink-test-utils-parent_flink-test-utils_src_main_resources_META-INF_NOTICE
cp flink-test-utils-parent/flink-test-utils/src/main/resources/META-INF/licenses/LICENSE.base64 %{buildroot}/usr/share/package-licenses/apache-flink/flink-test-utils-parent_flink-test-utils_src_main_resources_META-INF_licenses_LICENSE.base64
cp flink-test-utils-parent/flink-test-utils/src/main/resources/META-INF/licenses/LICENSE.jsr166y %{buildroot}/usr/share/package-licenses/apache-flink/flink-test-utils-parent_flink-test-utils_src_main_resources_META-INF_licenses_LICENSE.jsr166y
cp flink-test-utils-parent/flink-test-utils/src/main/resources/META-INF/licenses/LICENSE.jzlib %{buildroot}/usr/share/package-licenses/apache-flink/flink-test-utils-parent_flink-test-utils_src_main_resources_META-INF_licenses_LICENSE.jzlib
cp flink-test-utils-parent/flink-test-utils/src/main/resources/META-INF/licenses/LICENSE.webbit %{buildroot}/usr/share/package-licenses/apache-flink/flink-test-utils-parent_flink-test-utils_src_main_resources_META-INF_licenses_LICENSE.webbit
cp licenses-binary/LICENSE-hdrhistogram %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE-hdrhistogram
cp licenses-binary/LICENSE-protobuf %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE-protobuf
cp licenses-binary/LICENSE-re2j %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE-re2j
cp licenses-binary/LICENSE-stax2api %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE-stax2api
cp licenses-binary/LICENSE-xmlenc %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE-xmlenc
cp licenses-binary/LICENSE.angular %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.angular
cp licenses-binary/LICENSE.angular-drag-and-drop-list %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.angular-drag-and-drop-list
cp licenses-binary/LICENSE.angular-moment %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.angular-moment
cp licenses-binary/LICENSE.angular-ui-router %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.angular-ui-router
cp licenses-binary/LICENSE.arpack_combined_all %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.arpack_combined_all
cp licenses-binary/LICENSE.asm %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.asm
cp licenses-binary/LICENSE.base64 %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.base64
cp licenses-binary/LICENSE.bootstrap %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.bootstrap
cp licenses-binary/LICENSE.core %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.core
cp licenses-binary/LICENSE.d3 %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.d3
cp licenses-binary/LICENSE.dagre %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.dagre
cp licenses-binary/LICENSE.dagre-d3 %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.dagre-d3
cp licenses-binary/LICENSE.ev-emitter %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.ev-emitter
cp licenses-binary/LICENSE.font-awesome %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.font-awesome
cp licenses-binary/LICENSE.graphlib %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.graphlib
cp licenses-binary/LICENSE.grizzled-slf4j %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.grizzled-slf4j
cp licenses-binary/LICENSE.imagesloaded %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.imagesloaded
cp licenses-binary/LICENSE.influx %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.influx
cp licenses-binary/LICENSE.janino %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.janino
cp licenses-binary/LICENSE.jline %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.jline
cp licenses-binary/LICENSE.jquery %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.jquery
cp licenses-binary/LICENSE.jsr166y %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.jsr166y
cp licenses-binary/LICENSE.jtransforms %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.jtransforms
cp licenses-binary/LICENSE.jython %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.jython
cp licenses-binary/LICENSE.jzlib %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.jzlib
cp licenses-binary/LICENSE.kryo %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.kryo
cp licenses-binary/LICENSE.lodash %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.lodash
cp licenses-binary/LICENSE.machinist %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.machinist
cp licenses-binary/LICENSE.minlog %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.minlog
cp licenses-binary/LICENSE.moment %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.moment
cp licenses-binary/LICENSE.moment-duration-format %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.moment-duration-format
cp licenses-binary/LICENSE.protobuf %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.protobuf
cp licenses-binary/LICENSE.qtip2 %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.qtip2
cp licenses-binary/LICENSE.scala %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.scala
cp licenses-binary/LICENSE.scopt %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.scopt
cp licenses-binary/LICENSE.slf4j %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.slf4j
cp licenses-binary/LICENSE.slf4j-api %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.slf4j-api
cp licenses-binary/LICENSE.spire %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.spire
cp licenses-binary/LICENSE.split %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.split
cp licenses-binary/LICENSE.webbit %{buildroot}/usr/share/package-licenses/apache-flink/licenses-binary_LICENSE.webbit
cp licenses/LICENSE.angular %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.angular
cp licenses/LICENSE.angular-drag-and-drop-list %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.angular-drag-and-drop-list
cp licenses/LICENSE.angular-moment %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.angular-moment
cp licenses/LICENSE.angular-ui-router %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.angular-ui-router
cp licenses/LICENSE.bootstrap %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.bootstrap
cp licenses/LICENSE.d3 %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.d3
cp licenses/LICENSE.dagre %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.dagre
cp licenses/LICENSE.dagre-d3 %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.dagre-d3
cp licenses/LICENSE.ev-emitter %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.ev-emitter
cp licenses/LICENSE.font-awesome %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.font-awesome
cp licenses/LICENSE.graphlib %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.graphlib
cp licenses/LICENSE.imagesloaded %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.imagesloaded
cp licenses/LICENSE.jquery %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.jquery
cp licenses/LICENSE.lodash %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.lodash
cp licenses/LICENSE.moment %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.moment
cp licenses/LICENSE.moment-duration-format %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.moment-duration-format
cp licenses/LICENSE.qtip2 %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.qtip2
cp licenses/LICENSE.split %{buildroot}/usr/share/package-licenses/apache-flink/licenses_LICENSE.split
for targetdir in $(find . -type d -name target); do
pushd $targetdir
export GROUP_PATH=$(xml sel -t -v '/_:project/_:groupId' -v '/_:project/_:parent/_:groupId' ../pom.xml | sed 's#\.#/#g' | head -1)
export ARTIFACT_ID=$(xml sel -t -v '/_:project/_:artifactId' ../pom.xml | head -1)
export VERSION=$(xml sel -t -v '/_:project/_:version' -v '/_:project/_:parent/_:version' ../pom.xml | head -1)
export DEPLOY_PATH=%{buildroot}/usr/share/java/.m2/repository/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}
mkdir -p ${DEPLOY_PATH}
shopt -s nullglob
for jarfile in ${ARTIFACT_ID}*.jar; do
cp -p "${jarfile}" ${DEPLOY_PATH}/
done
rm -f ${DEPLOY_PATH}/${ARTIFACT_ID}-${VERSION}-sources.jar
cp -p ../pom.xml ${DEPLOY_PATH}/${ARTIFACT_ID}-${VERSION}.pom
popd
done
## install_append content
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/flink
cp -r flink-dist/target/flink-*-bin/flink-* %{buildroot}/usr/share/flink
mv %{buildroot}/usr/share/flink/LICENSE %{buildroot}/usr/share/doc/flink/
mv %{buildroot}/usr/share/flink/NOTICE %{buildroot}/usr/share/doc/flink/
mv %{buildroot}/usr/share/flink/README.txt %{buildroot}/usr/share/doc/flink/
mv %{buildroot}/usr/share/flink/licenses %{buildroot}/usr/share/doc/flink/
mkdir -p %{buildroot}/usr/share/defaults/flink
cp  %{buildroot}/usr/share/flink/conf/* %{buildroot}/usr/share/defaults/flink/
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/flink/flink-conf.yaml
/usr/share/defaults/flink/log4j-cli.properties
/usr/share/defaults/flink/log4j-console.properties
/usr/share/defaults/flink/log4j-yarn-session.properties
/usr/share/defaults/flink/log4j.properties
/usr/share/defaults/flink/logback-console.xml
/usr/share/defaults/flink/logback-yarn.xml
/usr/share/defaults/flink/logback.xml
/usr/share/defaults/flink/masters
/usr/share/defaults/flink/slaves
/usr/share/defaults/flink/sql-client-defaults.yaml
/usr/share/defaults/flink/zoo.cfg
/usr/share/flink/bin/config.sh
/usr/share/flink/bin/flink
/usr/share/flink/bin/flink-console.sh
/usr/share/flink/bin/flink-daemon.sh
/usr/share/flink/bin/flink.bat
/usr/share/flink/bin/historyserver.sh
/usr/share/flink/bin/jobmanager.sh
/usr/share/flink/bin/mesos-appmaster-job.sh
/usr/share/flink/bin/mesos-appmaster.sh
/usr/share/flink/bin/mesos-taskmanager.sh
/usr/share/flink/bin/pyflink-stream.sh
/usr/share/flink/bin/pyflink.bat
/usr/share/flink/bin/pyflink.sh
/usr/share/flink/bin/sql-client.sh
/usr/share/flink/bin/standalone-job.sh
/usr/share/flink/bin/start-cluster.bat
/usr/share/flink/bin/start-cluster.sh
/usr/share/flink/bin/start-scala-shell.sh
/usr/share/flink/bin/start-zookeeper-quorum.sh
/usr/share/flink/bin/stop-cluster.sh
/usr/share/flink/bin/stop-zookeeper-quorum.sh
/usr/share/flink/bin/taskmanager.sh
/usr/share/flink/bin/yarn-session.sh
/usr/share/flink/bin/zookeeper.sh
/usr/share/flink/conf/flink-conf.yaml
/usr/share/flink/conf/log4j-cli.properties
/usr/share/flink/conf/log4j-console.properties
/usr/share/flink/conf/log4j-yarn-session.properties
/usr/share/flink/conf/log4j.properties
/usr/share/flink/conf/logback-console.xml
/usr/share/flink/conf/logback-yarn.xml
/usr/share/flink/conf/logback.xml
/usr/share/flink/conf/masters
/usr/share/flink/conf/slaves
/usr/share/flink/conf/sql-client-defaults.yaml
/usr/share/flink/conf/zoo.cfg
/usr/share/flink/examples/batch/ConnectedComponents.jar
/usr/share/flink/examples/batch/DistCp.jar
/usr/share/flink/examples/batch/EnumTriangles.jar
/usr/share/flink/examples/batch/KMeans.jar
/usr/share/flink/examples/batch/PageRank.jar
/usr/share/flink/examples/batch/TransitiveClosure.jar
/usr/share/flink/examples/batch/WebLogAnalysis.jar
/usr/share/flink/examples/batch/WordCount.jar
/usr/share/flink/examples/gelly/flink-gelly-examples_2.12-1.8.1.jar
/usr/share/flink/examples/python/batch/TPCHQuery10.py
/usr/share/flink/examples/python/batch/TPCHQuery3.py
/usr/share/flink/examples/python/batch/TriangleEnumeration.py
/usr/share/flink/examples/python/batch/WebLogAnalysis.py
/usr/share/flink/examples/python/batch/WordCount.py
/usr/share/flink/examples/python/batch/__init__.py
/usr/share/flink/examples/python/streaming/fibonacci.py
/usr/share/flink/examples/python/streaming/word_count.py
/usr/share/flink/examples/streaming/IncrementalLearning.jar
/usr/share/flink/examples/streaming/Iteration.jar
/usr/share/flink/examples/streaming/SessionWindowing.jar
/usr/share/flink/examples/streaming/SocketWindowWordCount.jar
/usr/share/flink/examples/streaming/StateMachineExample.jar
/usr/share/flink/examples/streaming/TopSpeedWindowing.jar
/usr/share/flink/examples/streaming/Twitter.jar
/usr/share/flink/examples/streaming/WindowJoin.jar
/usr/share/flink/examples/streaming/WordCount.jar
/usr/share/flink/lib/flink-dist_2.12-1.8.1.jar
/usr/share/flink/lib/log4j-1.2.17.jar
/usr/share/flink/lib/slf4j-log4j12-1.7.15.jar
/usr/share/flink/opt/flink-cep-scala_2.12-1.8.1.jar
/usr/share/flink/opt/flink-cep_2.12-1.8.1.jar
/usr/share/flink/opt/flink-gelly-scala_2.12-1.8.1.jar
/usr/share/flink/opt/flink-gelly_2.12-1.8.1.jar
/usr/share/flink/opt/flink-metrics-datadog-1.8.1.jar
/usr/share/flink/opt/flink-metrics-graphite-1.8.1.jar
/usr/share/flink/opt/flink-metrics-influxdb-1.8.1.jar
/usr/share/flink/opt/flink-metrics-prometheus-1.8.1.jar
/usr/share/flink/opt/flink-metrics-slf4j-1.8.1.jar
/usr/share/flink/opt/flink-metrics-statsd-1.8.1.jar
/usr/share/flink/opt/flink-ml_2.12-1.8.1.jar
/usr/share/flink/opt/flink-oss-fs-hadoop-1.8.1.jar
/usr/share/flink/opt/flink-python_2.12-1.8.1.jar
/usr/share/flink/opt/flink-queryable-state-runtime_2.12-1.8.1.jar
/usr/share/flink/opt/flink-s3-fs-hadoop-1.8.1.jar
/usr/share/flink/opt/flink-s3-fs-presto-1.8.1.jar
/usr/share/flink/opt/flink-sql-client_2.12-1.8.1.jar
/usr/share/flink/opt/flink-streaming-python_2.12-1.8.1.jar
/usr/share/flink/opt/flink-swift-fs-hadoop-1.8.1.jar
/usr/share/flink/opt/flink-table_2.12-1.8.1.jar

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/flink/LICENSE
/usr/share/doc/flink/NOTICE
/usr/share/doc/flink/README.txt
/usr/share/doc/flink/licenses/LICENSE-hdrhistogram
/usr/share/doc/flink/licenses/LICENSE-protobuf
/usr/share/doc/flink/licenses/LICENSE-re2j
/usr/share/doc/flink/licenses/LICENSE-stax2api
/usr/share/doc/flink/licenses/LICENSE-xmlenc
/usr/share/doc/flink/licenses/LICENSE.angular
/usr/share/doc/flink/licenses/LICENSE.angular-drag-and-drop-list
/usr/share/doc/flink/licenses/LICENSE.angular-moment
/usr/share/doc/flink/licenses/LICENSE.angular-ui-router
/usr/share/doc/flink/licenses/LICENSE.arpack_combined_all
/usr/share/doc/flink/licenses/LICENSE.asm
/usr/share/doc/flink/licenses/LICENSE.base64
/usr/share/doc/flink/licenses/LICENSE.bootstrap
/usr/share/doc/flink/licenses/LICENSE.core
/usr/share/doc/flink/licenses/LICENSE.d3
/usr/share/doc/flink/licenses/LICENSE.dagre
/usr/share/doc/flink/licenses/LICENSE.dagre-d3
/usr/share/doc/flink/licenses/LICENSE.ev-emitter
/usr/share/doc/flink/licenses/LICENSE.font-awesome
/usr/share/doc/flink/licenses/LICENSE.graphlib
/usr/share/doc/flink/licenses/LICENSE.grizzled-slf4j
/usr/share/doc/flink/licenses/LICENSE.imagesloaded
/usr/share/doc/flink/licenses/LICENSE.influx
/usr/share/doc/flink/licenses/LICENSE.janino
/usr/share/doc/flink/licenses/LICENSE.jline
/usr/share/doc/flink/licenses/LICENSE.jquery
/usr/share/doc/flink/licenses/LICENSE.jsr166y
/usr/share/doc/flink/licenses/LICENSE.jtransforms
/usr/share/doc/flink/licenses/LICENSE.jython
/usr/share/doc/flink/licenses/LICENSE.jzlib
/usr/share/doc/flink/licenses/LICENSE.kryo
/usr/share/doc/flink/licenses/LICENSE.lodash
/usr/share/doc/flink/licenses/LICENSE.machinist
/usr/share/doc/flink/licenses/LICENSE.minlog
/usr/share/doc/flink/licenses/LICENSE.moment
/usr/share/doc/flink/licenses/LICENSE.moment-duration-format
/usr/share/doc/flink/licenses/LICENSE.protobuf
/usr/share/doc/flink/licenses/LICENSE.qtip2
/usr/share/doc/flink/licenses/LICENSE.scala
/usr/share/doc/flink/licenses/LICENSE.scopt
/usr/share/doc/flink/licenses/LICENSE.slf4j
/usr/share/doc/flink/licenses/LICENSE.slf4j-api
/usr/share/doc/flink/licenses/LICENSE.spire
/usr/share/doc/flink/licenses/LICENSE.split
/usr/share/doc/flink/licenses/LICENSE.webbit
